# Homework 1 : Exercice 2

## Import the data

In [1]:
import numpy as np

In [2]:
x1=np.array([ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1] ])

x2=np.array([ [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1] ])

x3=np.array([ [ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1] ])

x4= np.array([ [ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1] ])

x5= np.array([ [ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, 1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1] ])

In [3]:
def show_digit_pattern(x):
    for ligne in x:
        for px in ligne:
            if px == 1:
                print("1",end="")
            else:
                print(" ",end="")
        print("")

In [4]:
show_digit_pattern(x1)

          
   1111   
  111111  
 111  111 
 111  111 
 111  111 
 111  111 
 111  111 
 111  111 
 111  111 
 111  111 
 111  111 
 111  111 
  111111  
   1111   
          


In [5]:
def pre_process(image):
    return image.flatten()

def post_process(image_flatten):
    return image_flatten.reshape(x1.shape)

In [6]:
U = np.array([pre_process(x1),pre_process(x2),pre_process(x3),pre_process(x4),pre_process(x5)])
U.shape

(5, 160)

In [7]:
show_digit_pattern(post_process(U[4]))

 11    11 
 11    11 
 11    11 
 11    11 
 11    11 
 11    11 
 11    11 
 11111111 
 11111111 
       11 
       11 
       11 
       11 
       11 
       11 
       11 


In [8]:
U[0]-1 in U

False

## Create the HopfieldNetwork

In [9]:
def sign(x):
    return 1*(x >=0) - 1*(x <0)

In [10]:
sign(np.array([1,-1,1,-1,0]))

array([ 1, -1,  1, -1,  1])

In [11]:
class HopfieldNetwork:
    
    def _compute_weight(self,diag_null):
        W = (self.patterns@self.patterns.T)/self.N
        if diag_null:
            np.fill_diagonal(W,0) 
        return W
            
        
    def __init__(self,patterns,diag_null=True):
        self.patterns = patterns
        self.N = self.patterns.shape[0]
        self.P = self.patterns.shape[1]
        
        self.W = self._compute_weight(diag_null)
    
    def _next_step(self,s,asyncro = True,random=False):
            
        if asyncro:
            if random:
                i=np.random.randint(s.shape[0])
                s[i] = sign(self.W[i,:]@s)
                return s
            else:  
                for i in range(s.shape[0]):
                    s[i] = sign(self.W[i,:]@s)
                return s
        else:  
            return sign(self.W@s)
    
    def _show_pattern(self,s):
        pass
    
    def converge_to_steady_state(self,s,nb_iteration=100,asyncro=True,random_async=False,stdout = True):
        
        i = 0
        continue_var = True
        
        while continue_var and i<nb_iteration:
        
            old_s = s
            s =self._next_step(s,asyncro,random_async)
        
            if stdout:
                print(f"{i}\n")
                self._show_pattern(s)

            if(s==old_s).all() and not(asyncro):
                continue_var = False
            
            i = i+1
            
        return s

class DigitRecoHNetwok(HopfieldNetwork):
    
    def _show_pattern(self,p):
        show_digit_pattern(post_process(p))

In [12]:
digit_reco_network = DigitRecoHNetwok(U.T)

In [13]:
digit_reco_network.W.shape

(160, 160)

## Try the network on a test pattern

### a)

In [14]:
pattern_1 = np.array([[-1, 1, 1, 1, 1, -1, 1, 1, -1, -1], [-1, 1, 1, 1, 1, -1, 1, 1, -1, -1], [1, -1, -1, -1, -1, -1, 1, 1, -1, -1], [1, -1, -1, -1, -1, -1, 1, 1, -1, -1], [1, -1, -1, -1, -1, -1, 1, 1, -1, -1], [1, -1, -1, -1, -1, -1, 1, 1, -1, -1], [1, -1, -1, -1, -1, -1, 1, 1, -1, -1], [-1, 1, 1, 1, 1, -1, 1, 1, -1, -1], [-1, 1, 1, 1, 1, -1, 1, 1, -1, -1], [-1, 1, 1, -1, -1, 1, -1, -1, -1, -1], [-1, 1, 1, -1, -1, 1, -1, -1, -1, -1], [-1, 1, 1, -1, -1, 1, -1, -1, -1, -1], [-1, 1, 1, -1, -1, 1, -1, -1, -1, -1], [-1, 1, 1, -1, -1, 1, -1, -1, -1, -1], [-1, 1, 1, 1, 1, -1, 1, 1, -1, -1], [-1, 1, 1, 1, 1, -1, 1, 1, -1, -1]] )

In [15]:
show_digit_pattern(pattern_1)

 1111 11  
 1111 11  
1     11  
1     11  
1     11  
1     11  
1     11  
 1111 11  
 1111 11  
 11  1    
 11  1    
 11  1    
 11  1    
 11  1    
 1111 11  
 1111 11  


In [16]:
p1 = pattern_1.flatten()
p1_steady = digit_reco_network.converge_to_steady_state(p1,nb_iteration=5000,stdout=False)
show_digit_pattern(post_process(p1_steady))
post_process(p1_steady)

11111111  
11111111  
     111  
     111  
     111  
     111  
     111  
11111111  
11111111  
111       
111       
111       
111       
111       
11111111  
11111111  


array([[ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
       [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
       [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
       [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
       [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
       [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
       [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1]])

### b)

In [17]:
pattern_2 = np.array([[1, -1, 1, -1, 1, -1, 1, -1, 1, -1], [1, -1, 1, 1, -1, 1, -1, -1, 1, -1], [1, -1, -1, 1, -1, 1, -1, 1, 1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, 1, -1, 1, 1, -1, -1, 1, -1, -1], [1, -1, -1, 1, -1, 1, -1, 1, 1, -1], [1, -1, 1, 1, -1, 1, -1, -1, 1, -1], [1, -1, 1, -1, 1, -1, 1, -1, 1, -1]] )

In [18]:
p2 = pattern_2.flatten()

In [19]:
show_digit_pattern(post_process(p2))

1 1 1 1 1 
1 11 1  1 
1  1 1 11 
11 11  1  
11 11  1  
11 11  1  
11 11  1  
11 11  1  
11 11  1  
11 11  1  
11 11  1  
11 11  1  
11 11  1  
1  1 1 11 
1 11 1  1 
1 1 1 1 1 


In [20]:
p2 = pattern_2.flatten()
p2_steady = digit_reco_network.converge_to_steady_state(p2,nb_iteration=10000,stdout=False)
show_digit_pattern(post_process(p2_steady))
post_process(p2_steady)

111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111
111    111


array([[ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1]])

### c)

In [21]:
pattern_3 = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, -1, -1, -1, -1, 1, 1, 1], [1, 1, -1, -1, -1, -1, -1, -1, 1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, 1, -1, -1, -1, -1, -1, -1, 1, 1], [1, 1, 1, -1, -1, -1, -1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]] )

In [22]:
show_digit_pattern(pattern_3)

1111111111
111    111
11      11
1   11   1
1   11   1
1   11   1
1   11   1
1   11   1
1   11   1
1   11   1
1   11   1
1   11   1
1   11   1
11      11
111    111
1111111111


In [23]:
p3 = pre_process(pattern_3)

In [24]:
post_process(digit_reco_network.converge_to_steady_state(p3,stdout=False))

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1, -1, -1, -1, -1, -1, -1,  1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1,  1, -1, -1, -1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

### Emma

In [25]:
pattern_4 = np.array([[1, -1, 1, 1, -1, -1, -1, -1, 1, 1], [-1, 1, 1, 1, -1, 1, -1, -1, 1, -1], [-1, 1, -1, -1, -1, 1, -1, 1, -1, 1], [-1, 1, -1, 1, -1, 1, 1, 1, -1, 1], [-1, 1, 1, 1, 1, -1, -1, -1, 1, 1], [1, -1, 1, 1, -1, -1, -1, 1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, 1, 1, -1, -1, 1, -1, 1], [1, -1, -1, 1, 1, 1, -1, -1, 1, 1], [1, 1, 1, -1, 1, -1, -1, 1, -1, 1], [1, -1, 1, -1, 1, -1, 1, -1, 1, -1], [1, -1, 1, -1, -1, 1, -1, 1, -1, -1], [1, 1, -1, -1, -1, -1, 1, 1, -1, 1], [-1, 1, -1, -1, -1, 1, -1, 1, -1, 1], [-1, -1, -1, -1, -1, 1, 1, -1, 1, -1], [1, -1, -1, 1, -1, 1, -1, -1, -1, -1]])

In [26]:
p4 = pattern_4.flatten()
p4_steady = digit_reco_network.converge_to_steady_state(p4,nb_iteration=10000,stdout=False)
show_digit_pattern(post_process(p4_steady))
post_process(p4_steady)

111    111
111    111
111     11
111 1   11
111 1   11
111 1   11
111 1   11
11      11
11      11
111 11 111
111 11 111
111 11 111
111 11 111
111    111
111    111
111    111


array([[ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1, -1, -1, -1, -1, -1, -1,  1,  1],
       [ 1,  1, -1, -1, -1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1]])